# Simple workflow for deploying static content to GitHub Pages
name: Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_tag:
        description: '請輸入語意化版本標籤 (例如: v1.0.0)' # Input for semantic version tag
        required: true
        type: string
  push:
    tags:
      - 'v*' # Trigger when pushing semantic version tags like v1.0.0, v1.0.0a1, etc.

defaults:
  run:
    shell: bash

jobs:
  release:
    environment: Action Env
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      # Prefer manual input when dispatched; otherwise use the pushed tag name
      VERSION_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version_tag || github.ref_name }}
    steps:
      - name: Validate version tag (PEP 440)
        run: |
          echo "Validating VERSION_TAG: ${VERSION_TAG}"
          # Allow: vMAJOR.MINOR.PATCH or vMAJOR.MINOR.PATCHaN/bN/rcN (PEP 440 pre-releases)
          REGEX='^v[0-9]+\.[0-9]+\.[0-9]+((a|b|rc)[0-9]+)?$'
          if [[ ! "$VERSION_TAG" =~ $REGEX ]]; then
            echo "❌ Invalid VERSION_TAG: $VERSION_TAG"
            echo "Expected (PEP 440): vMAJOR.MINOR.PATCH or vMAJOR.MINOR.PATCHaN/bN/rcN"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build
        run: uv run python main.py release --locationiq-api-key "${{ secrets.LOCATIONIQ_API_KEY }}" --country-code "KR" "TH"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION_TAG }} # Use input when manual or the pushed tag name
          artifacts: "output/release.*"
          draft: false
          generateReleaseNotes: false # Keep false unless you want auto-generated notes
          commit: main # Or specify the commit SHA/branch if needed
          tag: ${{ env.VERSION_TAG }} # Use input when manual or the pushed tag
          makeLatest: ${{ !contains(env.VERSION_TAG, 'a') && !contains(env.VERSION_TAG, 'b') && !contains(env.VERSION_TAG, 'rc') && !contains(env.VERSION_TAG, 'alpha') && !contains(env.VERSION_TAG, 'beta') }} # Only mark stable versions as latest
          prerelease: ${{ contains(env.VERSION_TAG, 'a') || contains(env.VERSION_TAG, 'b') || contains(env.VERSION_TAG, 'rc') || contains(env.VERSION_TAG, 'alpha') || contains(env.VERSION_TAG, 'beta') }} # Mark alpha/beta/rc as pre-release
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto update reverse geocoding data on ${{ env.TODAY }}
          file_pattern: meta_data/*
